create database discussion_service;
use discussion_service;

CREATE TABLE discussion (
  DiscussionID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CourseID INT UNSIGNED NOT NULL,
  UserID INT UNSIGNED NOT NULL,
  Content TEXT NOT NULL,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE discussion_reply (
  ReplyID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  DiscussionID INT UNSIGNED NOT NULL,
  UserID INT UNSIGNED NOT NULL,
  Content TEXT NOT NULL,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (DiscussionID) REFERENCES discussion(DiscussionID) ON DELETE CASCADE
);