CREATE TABLE discussion (
  DiscussionID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CourseID INT UNSIGNED NOT NULL,
  UserID INT UNSIGNED NOT NULL,
  Content TEXT NOT NULL,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (CourseID) REFERENCES course(CourseID) ON DELETE CASCADE,
  FOREIGN KEY (UserID) REFERENCES user(UserID) ON DELETE CASCADE
);

CREATE TABLE discussion_reply (
  ReplyID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  DiscussionID INT UNSIGNED NOT NULL,
  UserID INT UNSIGNED NOT NULL,
  Content TEXT NOT NULL,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (DiscussionID) REFERENCES discussion(DiscussionID) ON DELETE CASCADE,
  FOREIGN KEY (UserID) REFERENCES user(UserID) ON DELETE CASCADE
);