-- Bảng Payment (Thanh toán cho khóa học)
CREATE TABLE payment (
  PaymentID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  UserID INT UNSIGNED NOT NULL,
  CourseID INT UNSIGNED NOT NULL, -- Liên kết với Course Service
  PaymentCode TEXT DEFAULT NULL,
  Amount FLOAT DEFAULT NULL,
  Purpose VARCHAR(20) DEFAULT NULL,
  Status VARCHAR(10) DEFAULT NULL,
  CreateAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  ExpireAt DATETIME DEFAULT NULL,
  UpdateAt DATETIME DEFAULT NULL,
  FOREIGN KEY (UserID) REFERENCES user(UserID) ON DELETE CASCADE
);

-- Bảng SystemTransaction (Giao dịch hệ thống)
CREATE TABLE systemtransaction (
  SystemTransactionID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  PaymentID INT UNSIGNED NOT NULL,
  Amount FLOAT DEFAULT NULL,
  Message TEXT DEFAULT NULL,
  UserID INT UNSIGNED NOT NULL,
  BankName TEXT DEFAULT NULL,
  BankAccountNumber TEXT DEFAULT NULL,
  Status VARCHAR(10) DEFAULT NULL,
  CreateAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserID) REFERENCES user(UserID) ON DELETE CASCADE,
  FOREIGN KEY (PaymentID) REFERENCES payment(PaymentID) ON DELETE CASCADE
);

-- Bảng UserTransaction (Giao dịch của người dùng)
CREATE TABLE usertransaction (
  UserTransactionID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  PaymentID INT UNSIGNED NOT NULL,
  Amount FLOAT DEFAULT NULL,
  Message TEXT DEFAULT NULL,
  Bank TEXT DEFAULT NULL,
  BankAccountNumber TEXT DEFAULT NULL,
  CreateAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (PaymentID) REFERENCES payment(PaymentID) ON DELETE CASCADE
);