CREATE TABLE user (
  UserID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Email TEXT NOT NULL,
  HashPassword TEXT NOT NULL,
  PhoneNumber TEXT DEFAULT NULL,
  About TEXT DEFAULT NULL,
  AvatarLink TEXT DEFAULT NULL,
  BankName TEXT DEFAULT NULL,
  BankAccountNumber TEXT DEFAULT NULL,
  Role ENUM('student', 'teacher', 'admin') NOT NULL DEFAULT 'student',
  CreateAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  IsPremium DATETIME DEFAULT NULL
);

CREATE TABLE user_tokens (
    TokenID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    UserID INT UNSIGNED,
    FCM_token VARCHAR(255) NOT NULL,
    DeviceType VARCHAR(50),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES user(UserID) ON DELETE CASCADE
);